#if canImport(SwiftUI)
import SwiftUI

private struct KatanaResolverKey: EnvironmentKey {
    static let defaultValue: any Resolver = AnyResolver([:])
}

extension EnvironmentValues {
    /// The `Resolver` installed by ``SwiftUICore/View/katana(_:)``. Holds
    /// `any Resolver` so both `AnyResolver` and macro-generated typed snapshots
    /// can live in the environment behind the same key.
    public var katanaResolver: any Resolver {
        get { self[KatanaResolverKey.self] }
        set { self[KatanaResolverKey.self] = newValue }
    }
}

extension View {
    /// Installs a `Resolver` in the environment so descendant views can read
    /// dependencies declaratively with `@Inject`. Call this **once** at the
    /// composition root — there's no per-type wiring downstream.
    ///
    /// ```swift
    /// @main
    /// struct MyApp: App {
    ///     @State private var resolver: AnyResolver?
    ///     var body: some Scene {
    ///         WindowGroup {
    ///             if let resolver {
    ///                 RootView().katana(resolver)
    ///             } else {
    ///                 ProgressView().task {
    ///                     let container = await makeAppContainer()
    ///                     resolver = await container.snapshot()
    ///                 }
    ///             }
    ///         }
    ///     }
    /// }
    /// ```
    public func katana(_ resolver: any Resolver) -> some View {
        environment(\.katanaResolver, resolver)
    }
}

/// Reads a singleton from the ambient `Resolver` (installed with
/// ``SwiftUICore/View/katana(_:)``). The SwiftUI equivalent of Hilt's
/// `hiltViewModel()` — declare the type you need, the framework hands it over.
///
/// ```swift
/// struct ContentView: View {
///     @Inject var viewModel: TodoListViewModel
///     var body: some View { Text("\(viewModel.todos.count)") }
/// }
/// ```
///
/// `Inject` reads `any Resolver` from the environment, so it works with both
/// `AnyResolver` (runtime trap on miss) and macro-generated typed snapshots.
/// For compile-time-checked injection, use the `@AppName.Inject` wrapper
/// generated by the `@Container` macro on your graph class.
@propertyWrapper
public struct Inject<Value: Sendable>: DynamicProperty {
    @Environment(\.katanaResolver) private var resolver

    public init() {}

    public var wrappedValue: Value {
        resolver.resolve(Value.self)
    }
}
#endif
