import Foundation

/// Emits Swift source for `@Container` and `@TestContainer` declarations.
/// Storage lives in the macro-emitted stub; everything else (typed API,
/// `EnvironmentValues` slot, install modifier, bare `Inject.init()`) comes
/// from here.
public enum Emitter {

    public static func emit(
        containers: [ContainerDecl],
        scopes: [ScopeRegistryDecl] = [],
        modules: [String: ModuleDecl],
        imports: Set<ImportDecl> = []
    ) -> String {
        var output = """
            // Generated by KatanaCodegen — do not edit.
            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            import Katana

            """

        // Replay user imports so the generated file sees the same types user
        // files do. Critical for test targets using `@testable import` to
        // reach internal production types.
        for imp in imports.sorted(by: { $0.moduleName < $1.moduleName }) {
            let prefix = imp.isTestable ? "@testable " : ""
            output += "\(prefix)import \(imp.moduleName)\n"
        }
        output += "\n"

        // `ContainerScope.<case>` statics from collected `@Scope` enums.
        // Done at codegen time because peer macros can't introduce arbitrary
        // names at global scope.
        let allCases = scopes.flatMap(\.cases).filter { $0 != "default" }
        if !allCases.isEmpty {
            output += "extension ContainerScope {\n"
            for caseName in allCases.sorted() {
                output += "    public static let \(caseName) = ContainerScope(\"\(caseName)\")\n"
            }
            output += "}\n\n"
        }

        for container in containers.sorted(by: { $0.name < $1.name }) {
            let types = resolveTypes(for: container.modules, in: modules)
            if types.isEmpty { continue }
            output += emitContainer(container, types: types)
            output += "\n"
        }

        // Bare `@Inject var x: T` requires exactly one container at `.default`.
        let defaults = containers.filter { $0.scope == "default" }
        if defaults.count == 1 {
            output += "\n"
            output += emitInjectDefaultInit(for: defaults[0])
        }

        return output
    }

    private static func resolveTypes(for moduleNames: [String], in modules: [String: ModuleDecl]) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for name in moduleNames {
            guard let module = modules[name] else { continue }
            for type in module.types where seen.insert(type).inserted {
                result.append(type)
            }
        }
        return result
    }

    private static func emitContainer(_ container: ContainerDecl, types: [String]) -> String {
        let access = accessPrefix(container.accessLevel)
        let avail = container.availability.map { "\($0)\n" } ?? ""
        let name = container.name

        var body = "\(avail)extension \(name) {\n"

        body += "    \(access)convenience init(_ customize: (@Sendable (Container) async -> Void)? = nil) async {\n"
        body += "        let inner = Container()\n"
        for type in types {
            body += "        await inner.register(\(type).self)\n"
        }
        body += "        await customize?(inner)\n"
        body += "        self.init(__katanaContainer: inner)\n"
        body += "    }\n\n"

        for type in types {
            body += "    \(access)func resolve(_: \(type).Type) async -> \(type) {\n"
            body += "        await __katanaContainer.resolve(\(type).self)\n"
            body += "    }\n\n"
        }

        body += emitSnapshot(access: access, types: types, parent: name)
        body += "\n"
        body += emitSnapshotMethod(access: access, types: types)
        body += "\n"

        if container.isTest {
            body += "\n"
            body += emitOverrides(access: access)
        }

        body += "}\n\n"
        body += emitSwiftUIEnvironment(container: container, access: access)
        return body
    }

    private static func emitSnapshot(access: String, types: [String], parent: String) -> String {
        var body = "    \(access)struct Snapshot: Resolver {\n"
        for type in types {
            body += "        \(access)let \(propertyName(for: type)): \(type)\n"
        }
        body += "\n"
        let initParams = types.map { "\(propertyName(for: $0)): \($0)" }.joined(separator: ", ")
        body += "        \(access)init(\(initParams)) {\n"
        for type in types {
            body += "            self.\(propertyName(for: type)) = \(propertyName(for: type))\n"
        }
        body += "        }\n\n"
        for type in types {
            body += "        \(access)func resolve(_: \(type).Type) -> \(type) { \(propertyName(for: type)) }\n"
        }
        body += "\n"
        body += "        \(access)func resolve<T: Sendable>(_ type: T.Type) -> T {\n"
        body += "            switch ObjectIdentifier(type) {\n"
        for type in types {
            body += "            case ObjectIdentifier(\(type).self):\n"
            body += "                return \(propertyName(for: type)) as! T\n"
        }
        body += "            default:\n"
        body += "                preconditionFailure(\"\\(type) is not in \(parent).Snapshot. Add it to a registered @Module.\")\n"
        body += "            }\n"
        body += "        }\n"
        body += "    }\n"
        return body
    }

    private static func emitSnapshotMethod(access: String, types: [String]) -> String {
        var body = "    \(access)func snapshot() async -> Snapshot {\n"
        for type in types {
            body += "        let \(propertyName(for: type)) = await __katanaContainer.resolve(\(type).self)\n"
        }
        let args = types.map { "\(propertyName(for: $0)): \(propertyName(for: $0))" }.joined(separator: ", ")
        body += "        return Snapshot(\(args))\n"
        body += "    }\n"
        return body
    }

    private static func emitOverrides(access: String) -> String {
        var body = ""
        body += "    \(access)func override<T: Injectable & Sendable>(_ type: T.Type, with instance: T) async {\n"
        body += "        await __katanaContainer.override(type, with: instance)\n"
        body += "    }\n\n"
        body += "    \(access)func override<T: Injectable & Sendable>(\n"
        body += "        _ type: T.Type,\n"
        body += "        factory: @escaping @Sendable (Container) async -> T\n"
        body += "    ) async {\n"
        body += "        await __katanaContainer.override(type, factory: factory)\n"
        body += "    }\n"
        return body
    }

    private static func emitSwiftUIEnvironment(container: ContainerDecl, access: String) -> String {
        let envKey = envKeyName(for: container.scope)
        let keyType = "__Katana_\(container.name)_SnapshotKey"
        let avail = container.availability.map { "\($0)\n" } ?? ""
        let snapshotType = "\(container.name).Snapshot"

        var body = "#if canImport(SwiftUI)\n"
        body += "private struct \(keyType): EnvironmentKey {\n"
        body += "    static let defaultValue: (any Resolver)? = nil\n"
        body += "}\n\n"
        body += "\(avail)extension EnvironmentValues {\n"
        body += "    \(access)var \(envKey): (any Resolver)? {\n"
        body += "        get { self[\(keyType).self] }\n"
        body += "        set { self[\(keyType).self] = newValue }\n"
        body += "    }\n"
        body += "}\n\n"
        body += "\(avail)extension View {\n"
        body += "    \(access)func katana(_ snapshot: \(snapshotType)) -> some View {\n"
        body += "        environment(\\.\(envKey), snapshot)\n"
        body += "    }\n"
        body += "}\n"
        body += "#endif\n"
        return body
    }

    private static func emitInjectDefaultInit(for container: ContainerDecl) -> String {
        let access = accessPrefix(container.accessLevel)
        let avail = container.availability.map { "\($0)\n" } ?? ""
        let envKey = envKeyName(for: container.scope)

        var body = "#if canImport(SwiftUI)\n"
        body += "\(avail)extension Inject {\n"
        body += "    \(access)init() {\n"
        body += "        self.init(\\.\(envKey))\n"
        body += "    }\n"
        body += "}\n"
        body += "#endif\n"
        return body
    }

    /// `default` is a Swift keyword; the built-in scope uses `katanaDefault`
    /// for its `EnvironmentValues` accessor. Custom scopes use their case
    /// name verbatim, matching `@Inject(\.<scope>)`.
    private static func envKeyName(for scope: String) -> String {
        scope == "default" ? "katanaDefault" : scope
    }

    private static func accessPrefix(_ level: String) -> String {
        switch level {
        case "open", "public": return "public "
        case "": return ""
        default: return "\(level) "
        }
    }

    private static func propertyName(for typeName: String) -> String {
        guard let first = typeName.first else { return typeName }
        return first.lowercased() + typeName.dropFirst()
    }
}
