import Foundation

/// Emits Swift source for `@KatanaApp` and `@KatanaTestApp` declarations.
///
/// The emitted code is **structurally identical** to what `@Container` and
/// `@TestContainer` macros produce — same `__katanaContainer` accessor, typed
/// `resolve(_:)` overloads, nested `Snapshot`, nested `Inject` — except the
/// type list comes from aggregated `@Module`s instead of inline args, and the
/// storage lives in the macro-emitted `__katanaContainerStorage` (because
/// Swift extensions can't add stored properties).
public enum Emitter {

    public static func emit(
        apps: [AppDecl],
        testApps: [TestAppDecl],
        modules: [String: ModuleDecl]
    ) -> String {
        var output = """
            // Generated by KatanaCodegen — do not edit.
            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            import Katana


            """

        for app in apps.sorted(by: { $0.name < $1.name }) {
            let types = resolveTypes(for: app.modules, in: modules)
            if types.isEmpty { continue }
            output += emitApp(name: app.name, types: types, accessLevel: app.accessLevel, availability: app.availability)
            output += "\n"
        }

        for testApp in testApps.sorted(by: { $0.name < $1.name }) {
            guard let prod = apps.first(where: { $0.name == testApp.productionApp }) else {
                output += "#error(\"@KatanaTestApp(of: \(testApp.productionApp).self) references an unknown @KatanaApp.\")\n"
                continue
            }
            let types = resolveTypes(for: prod.modules, in: modules)
            if types.isEmpty { continue }
            output += emitTestApp(name: testApp.name, types: types, accessLevel: testApp.accessLevel, availability: testApp.availability)
            output += "\n"
        }

        return output
    }

    // MARK: - Resolution

    private static func resolveTypes(for moduleNames: [String], in modules: [String: ModuleDecl]) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for name in moduleNames {
            guard let module = modules[name] else { continue }
            for type in module.types where seen.insert(type).inserted {
                result.append(type)
            }
        }
        return result
    }

    // MARK: - App emission

    private static func emitApp(name: String, types: [String], accessLevel: String, availability: String?) -> String {
        let access = accessPrefix(accessLevel)
        let avail = availability.map { "\($0)\n" } ?? ""

        var body = ""
        body += "\(avail)extension \(name) {\n"

        // Async convenience init. Builds the inner Container, runs the optional
        // customize closure, then delegates to the macro-emitted designated
        // init that stashes the container. `App()` unambiguously matches this
        // overload because the designated init requires `__katanaContainer:`.
        body += "    \(access)convenience init(_ customize: (@Sendable (Container) async -> Void)? = nil) async {\n"
        body += "        let inner = Container()\n"
        for type in types {
            body += "        await inner.register(\(type).self)\n"
        }
        body += "        await customize?(inner)\n"
        body += "        self.init(__katanaContainer: inner)\n"
        body += "    }\n\n"

        // Typed resolve overloads.
        for type in types {
            body += "    \(access)func resolve(_: \(type).Type) async -> \(type) {\n"
            body += "        await __katanaContainer.resolve(\(type).self)\n"
            body += "    }\n\n"
        }

        body += emitSnapshot(access: access, types: types, parent: name)
        body += "\n"
        body += emitSnapshotMethod(access: access, types: types)
        body += "\n"
        body += emitInject(access: access, parent: name)

        body += "}\n"

        // SwiftUI environment plumbing — emitted as peers of the extension,
        // since the plugin (unlike a macro) can add extensions to other types
        // at file scope.
        body += "\n"
        body += emitSwiftUIEnvironment(access: access, parent: name, availability: availability)
        return body
    }

    private static func emitTestApp(name: String, types: [String], accessLevel: String, availability: String?) -> String {
        var body = emitApp(name: name, types: types, accessLevel: accessLevel, availability: availability)

        let access = accessPrefix(accessLevel)
        let avail = availability.map { "\($0)\n" } ?? ""

        body += "\n"
        body += "\(avail)extension \(name) {\n"
        body += "    \(access)func override<T: Injectable & Sendable>(_ type: T.Type, with instance: T) async {\n"
        body += "        await __katanaContainer.override(type, with: instance)\n"
        body += "    }\n\n"
        body += "    \(access)func override<T: Injectable & Sendable>(\n"
        body += "        _ type: T.Type,\n"
        body += "        factory: @escaping @Sendable (Container) async -> T\n"
        body += "    ) async {\n"
        body += "        await __katanaContainer.override(type, factory: factory)\n"
        body += "    }\n"
        body += "}\n\n"
        body += "\(avail)extension \(name): TestContainerMarker {}\n"

        return body
    }

    // MARK: - Components

    private static func emitSnapshot(access: String, types: [String], parent: String) -> String {
        var body = "    \(access)struct Snapshot: Resolver {\n"
        for type in types {
            body += "        \(access)let \(propertyName(for: type)): \(type)\n"
        }
        body += "\n"
        let initParams = types.map { "\(propertyName(for: $0)): \($0)" }.joined(separator: ", ")
        body += "        \(access)init(\(initParams)) {\n"
        for type in types {
            body += "            self.\(propertyName(for: type)) = \(propertyName(for: type))\n"
        }
        body += "        }\n\n"
        for type in types {
            body += "        \(access)func resolve(_: \(type).Type) -> \(type) { \(propertyName(for: type)) }\n"
        }
        body += "\n"
        body += "        \(access)func resolve<T: Sendable>(_ type: T.Type) -> T {\n"
        body += "            switch ObjectIdentifier(type) {\n"
        for type in types {
            body += "            case ObjectIdentifier(\(type).self):\n"
            body += "                return \(propertyName(for: type)) as! T\n"
        }
        body += "            default:\n"
        body += "                preconditionFailure(\"\\(type) is not in \(parent).Snapshot. Add it to a registered @Module.\")\n"
        body += "            }\n"
        body += "        }\n"
        body += "    }\n"
        return body
    }

    private static func emitSnapshotMethod(access: String, types: [String]) -> String {
        var body = "    \(access)func snapshot() async -> Snapshot {\n"
        for type in types {
            body += "        let \(propertyName(for: type)) = await __katanaContainer.resolve(\(type).self)\n"
        }
        let args = types.map { "\(propertyName(for: $0)): \(propertyName(for: $0))" }.joined(separator: ", ")
        body += "        return Snapshot(\(args))\n"
        body += "    }\n"
        return body
    }

    private static func emitInject(access: String, parent: String) -> String {
        let keyPath = environmentKeyName(for: parent)
        var body = "    #if canImport(SwiftUI)\n"
        body += "    @propertyWrapper\n"
        body += "    \(access)struct Inject<Value: Sendable>: DynamicProperty {\n"
        body += "        @Environment(\\.\(keyPath)) private var snapshot\n"
        body += "        \(access)init() {}\n"
        body += "        \(access)var wrappedValue: Value {\n"
        body += "            guard let snapshot else {\n"
        body += "                preconditionFailure(\"@\(parent).Inject expected \(parent).Snapshot in \\\\.\(keyPath). Install via `.environment(\\\\.\(keyPath), await \(parent)().snapshot())`.\")\n"
        body += "            }\n"
        body += "            return snapshot.resolve(Value.self)\n"
        body += "        }\n"
        body += "    }\n"
        body += "    #endif\n"
        return body
    }

    /// Emits the per-graph SwiftUI environment plumbing: a private
    /// `EnvironmentKey`, the `EnvironmentValues` extension property, and a
    /// `View` convenience modifier for installation. Lives at file scope, not
    /// inside the App's extension — peer-style emission only the plugin
    /// (not a macro) can do at global scope.
    private static func emitSwiftUIEnvironment(access: String, parent: String, availability: String?) -> String {
        let keyPath = environmentKeyName(for: parent)
        let keyType = "__Katana_\(parent)_SnapshotKey"
        let avail = availability.map { "\($0)\n" } ?? ""

        var body = "#if canImport(SwiftUI)\n"
        body += "private struct \(keyType): EnvironmentKey {\n"
        body += "    static let defaultValue: \(parent).Snapshot? = nil\n"
        body += "}\n\n"
        body += "\(avail)extension EnvironmentValues {\n"
        body += "    \(access)var \(keyPath): \(parent).Snapshot? {\n"
        body += "        get { self[\(keyType).self] }\n"
        body += "        set { self[\(keyType).self] = newValue }\n"
        body += "    }\n"
        body += "}\n\n"
        body += "\(avail)extension View {\n"
        body += "    /// Installs `\(parent).Snapshot` in the SwiftUI environment so descendant\n"
        body += "    /// views can read its dependencies with `@\(parent).Inject`.\n"
        body += "    \(access)func install\(parent)(_ snapshot: \(parent).Snapshot) -> some View {\n"
        body += "        environment(\\.\(keyPath), snapshot)\n"
        body += "    }\n"
        body += "}\n"
        body += "#endif\n"
        return body
    }

    private static func environmentKeyName(for className: String) -> String {
        // App → appSnapshot, CheckoutGraph → checkoutGraphSnapshot
        guard let first = className.first else { return "snapshot" }
        return first.lowercased() + className.dropFirst() + "Snapshot"
    }

    // MARK: - Misc

    private static func accessPrefix(_ level: String) -> String {
        switch level {
        case "open", "public": return "public "
        case "": return ""
        default: return "\(level) "
        }
    }

    private static func propertyName(for typeName: String) -> String {
        guard let first = typeName.first else { return typeName }
        return first.lowercased() + typeName.dropFirst()
    }
}
